import confetti from "canvas-confetti";

interface Guess {
  word: string;
  rank: number;
  timestamp: number;
}

interface GameState {
  targetWord: string;
  wordbank: string[];
  guesses: Guess[];
  latestGuess: Guess | null;
  isGameOver: boolean;
}

const state: GameState = {
  targetWord: "apple",
  wordbank: [],
  guesses: [],
  latestGuess: null,
  isGameOver: false,
};

// ⚡ High-Speed Lookup Layer (Solves the 370k linear scan performance lag)
const wordRankMap = new Map<string, number>();

// DOM Query Elements Cache
const guessForm = document.getElementById("guess-form") as HTMLFormElement;
const guessInput = document.getElementById("guess-input") as HTMLInputElement;
const guessListContainer = document.getElementById(
  "guess-list",
) as HTMLDivElement;
const latestGuessContainer = document.getElementById(
  "latest-guess-container",
) as HTMLDivElement;
const hintDisplayContainer = document.getElementById(
  "hint-display-container",
) as HTMLDivElement;
const guessCountDisplay = document.getElementById(
  "guess-count",
) as HTMLSpanElement;

const menuToggleBtn = document.getElementById(
  "menu-toggle-btn",
) as HTMLButtonElement;
const menuOptions = document.getElementById("menu-options") as HTMLDivElement;
const hintBtn = document.getElementById("hint-btn") as HTMLButtonElement;
const giveupBtn = document.getElementById("giveup-btn") as HTMLButtonElement;

function getTierClass(rank: number): "green" | "yellow" | "red" {
  if (rank >= 1 && rank <= 100) return "green";
  if (rank >= 101 && rank <= 500) return "yellow";
  return "red";
}

// Global Async Data Bootloader Loop
async function initGameEngine() {
  try {
    // Fetch the compiled database generated by the Python script
    const response = await fetch("/src/wordbank.json");
    if (!response.ok)
      throw new Error("Failed to load compiled wordbank configuration asset.");

    state.wordbank = await response.json();

    // The target word sits systematically compiled at index position 0
    state.targetWord = state.wordbank[0];

    // Build the high-speed O(1) index map out of the raw array data
    wordRankMap.clear();
    state.wordbank.forEach((word: string, index: number) => {
      wordRankMap.set(word, index);
    });

    console.log(
      `🚀 Game Engine loaded with ${state.wordbank.length.toLocaleString()} words.`,
    );
    console.log(`🎯 Current Target Word is armed and hidden.`);

    renderGame();
  } catch (error) {
    console.error("Engine Init Failure:", error);
    hintDisplayContainer.innerHTML = `<div class="hint-banner reveal-banner">⚠️ System initialization failure: Check wordbank.json path.</div>`;
  }
}

function renderGame(): void {
  if (state.latestGuess) {
    const tier = getTierClass(state.latestGuess.rank);
    latestGuessContainer.innerHTML = `
      <div class="latest-guess-box ${tier}">
        <div>
          <span class="latest-label">Latest Guess</span>
          <strong>${state.latestGuess.word}</strong>
        </div>
        <strong>#${state.latestGuess.rank}</strong>
      </div>
    `;
  } else {
    latestGuessContainer.innerHTML = "";
  }

  guessListContainer.innerHTML = "";
  const sortedGuesses = [...state.guesses].sort((a, b) => a.rank - b.rank);

  sortedGuesses.forEach((guess) => {
    const row = document.createElement("div");
    const tier = getTierClass(guess.rank);

    row.className = `guess-row ${tier}`;
    row.innerHTML = `
      <div class="word-wrapper">
        <span class="arrow-indicator">➔</span>
        <span class="word-text">${guess.word}</span>
      </div>
      <span class="rank-value">#${guess.rank}</span>
    `;
    guessListContainer.appendChild(row);
  });

  guessCountDisplay.textContent = `Guesses: ${state.guesses.length}`;
}

function handleGetHint(): void {
  menuOptions.classList.add("hidden");
  if (state.isGameOver || state.wordbank.length === 0) return;

  let currentClosestRank = state.wordbank.length;
  if (state.guesses.length > 0) {
    currentClosestRank = Math.min(...state.guesses.map((g) => g.rank));
  }

  if (currentClosestRank === 1) {
    hintDisplayContainer.innerHTML = `<div class="hint-banner">You found it already! No hints needed.</div>`;
    return;
  }

  let targetRank = currentClosestRank;

  if (currentClosestRank >= 2 && currentClosestRank <= 50) {
    targetRank = currentClosestRank - (Math.floor(Math.random() * 3) + 1);
  } else if (currentClosestRank >= 51 && currentClosestRank <= 100) {
    targetRank = currentClosestRank - (Math.floor(Math.random() * 8) + 3);
  } else if (currentClosestRank >= 101 && currentClosestRank <= 1000) {
    targetRank = currentClosestRank - (Math.floor(Math.random() * 91) + 10);
  } else {
    const offset = Math.floor(currentClosestRank * 0.17 + 143);
    targetRank = currentClosestRank - offset;
  }

  if (targetRank < 1) targetRank = 1;
  if (targetRank >= currentClosestRank) targetRank = currentClosestRank - 1;

  const hintWord = state.wordbank[targetRank - 1];
  hintDisplayContainer.innerHTML = `
    <div class="hint-banner">
      💡 Hint: Try looking towards a word like <strong>"${hintWord}"</strong> (Rank #${targetRank})
    </div>
  `;
}

function handleGiveUp(): void {
  menuOptions.classList.add("hidden");
  if (state.isGameOver) return;

  state.isGameOver = true;
  hintDisplayContainer.innerHTML = `
    <div class="hint-banner reveal-banner">
      🏳️ You surrendered! The secret word was <strong>"${state.targetWord}"</strong> (#1).
    </div>
  `;

  guessInput.disabled = true;
  document
    .querySelector("#guess-form button")
    ?.setAttribute("disabled", "true");
}

function handleGuessSubmit(event: Event): void {
  event.preventDefault();
  if (state.isGameOver || state.wordbank.length === 0) return;

  const rawWord = guessInput.value.trim().toLowerCase();
  if (!rawWord) return;

  // Optimized O(1) Map check replacing .indexOf() array scan
  if (!wordRankMap.has(rawWord)) {
    alert(`"${rawWord}" is not in the semantic database dictionary.`);
    guessInput.value = "";
    return;
  }

  const wordIndex = wordRankMap.get(rawWord)!;
  const computedRank = wordIndex + 1;

  const alreadyGuessed = state.guesses.some((g) => g.word === rawWord);
  if (alreadyGuessed) {
    alert("You've already tried this word!");
    guessInput.value = "";
    return;
  }

  const newGuess: Guess = {
    word: rawWord,
    rank: computedRank,
    timestamp: Date.now(),
  };

  state.guesses.push(newGuess);
  state.latestGuess = newGuess;
  guessInput.value = "";

  if (computedRank === 1) {
    state.isGameOver = true;
    hintDisplayContainer.innerHTML = "";
    confetti({ particleCount: 150, spread: 80, origin: { y: 0.6 } });
    setTimeout(
      () =>
        alert(
          `🎉 Incredible! You found the secret word in ${state.guesses.length} attempts!`,
        ),
      250,
    );
  }

  renderGame();
}

guessForm.addEventListener("submit", handleGuessSubmit);
menuToggleBtn.addEventListener("click", (e) => {
  e.stopPropagation();
  menuOptions.classList.toggle("hidden");
});
document.addEventListener("click", () => {
  menuOptions.classList.add("hidden");
});
hintBtn.addEventListener("click", handleGetHint);
giveupBtn.addEventListener("click", handleGiveUp);

// Start the game loop engine
initGameEngine();
